TOPDIR ?= ../..
include $(TOPDIR)/.config

$(RFID_SUPPORT)_SRC += hardware/rfid/em4095.c
$(RFID_SUPPORT)_SRC += hardware/rfid/rfid.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
