TOPDIR ?= ../..
include $(TOPDIR)/.config

$(LCDMENU_SUPPORT)_SRC += services/lcd-menu/lcd_menu.c
#$(LCD-MENU_SUPPORT)_SRC += services/lcd-menu/

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
