TOPDIR ?= ..
include $(TOPDIR)/.config

$(WEBSOCKETS_SUPPORT)_SRC += protocols/websockets/websockets.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

