TOPDIR ?= ../..
include $(TOPDIR)/.config

$(INTEWAMONITOR_PROTOCOL_SUPPORT)_SRC += protocols/udpintewa/udpintewa_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
